### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by juanmirocks** [Rostlab/ConSurf#1]
I haven't seen anything created yet ?

**Comment by GrimSmiler** [comment]
I haven't created anything yet, that is true.

So far i was struggling with git svn clone command.
I didn't allow me to an error:

No address associated with hostname: Unable to connect to a repository at URL 'svn:///localhost/svn-consurf': Unknown hostname '' at /usr/share/perl5/Git/SVN.pm line 305.

I could resolve the issue only yesterday, but because i was not sure if i preserved all the history and done everything correctly i didn't publish it on git.

Tomorrow i will be able to do the presentation about the first phase. (Readme, issues during transfer, and etc.)

**Comment by GrimSmiler** [comment]
Cloned the SVN repo to GitHub using SourceTree.
Currently there exists 2 branches: master and develop.
Starting work on ReadMe for develop branch.

**Comment by juanmirocks** [comment]
Great. Please remember there is NOT exercise tomorrow. Just make sure you
commit everything necessary for me to install and run the method. That is,
have a nice simple but comprehensive README.md

**Comment by GrimSmiler** [comment]
Sure. If i will not be able to run the tool i'll notify You and come by tomorrow if You do not mind.

**Comment by GrimSmiler** [comment]
Update.

Copied the Readme from the master branch. Made some adoption to make it look a bit better with Markdown.
Was struggling with Vagrant. Currently trying to install Rate4Site on vagrant box (using debian/wheezy64).
Planning creating a feature branch with Vagrant solution in there.
Did not prepare a Readme according to the template due to inability to successfully start ConSurf.

Readme from master branch looks ok enough, but will be changed in future according to the template.

**Comment by juanmirocks** [comment]
Thank you Ilyan (I believe ? :P)

I've just made the develop branch the default one. Work on that one only for now. Once we are happy with the stability of the system we make a release and merge to master. And we could also merge both READMEs to have better into.

Feel free to come over by my office today, considering all the initial problemas you had.

**Comment by GrimSmiler** [comment]
Sure. Sounds good to me. I'll come by after Prof. Rost finishes the lecture.

P.S. You are almost correct, it is Ilya :) without the "n" ;)

On чт, дек. 10, 2015 at 10:28 AM, Juan Miguel Cejuela < notifications@github.com [notifications@github.com] > wrote:
Thank you Ilyan (I believe ? :P)

I've just made the develop branch the default one. Work on that one only for
now. Once we are happy with the stability of the system we make a release and
merge to master. And we could also merge both READMEs to have better into.

Feel free to come over by my office today, considering all the initial problemas
you had.

—
Reply to this email directly or view it on GitHub
[https://github.com/Rostlab/ConSurf/issues/1#issuecomment-163546090] .[https://github.com/notifications/beacon/AExpfXmB7iH8MmYnPe5vlGezEfCv4xvEks5pOT1XgaJpZM4Gxm1g.gif]

**Comment by juanmirocks** [comment]
(I am from 13:30 there on)

**Comment by GrimSmiler** [comment]
Got it.

Best Regards, Ilya Migal On чт, дек. 10, 2015 at 11:08 AM, Juan Miguel Cejuela < notifications@github.com [notifications@github.com] > wrote:
(I am from 13:30 there on)

—
Reply to this email directly or view it on GitHub
[https://github.com/Rostlab/ConSurf/issues/1#issuecomment-163563492] .[https://github.com/notifications/beacon/AExpfRRAdPTMVJYNA90N9f5io_Fut-daks5pOUaagaJpZM4Gxm1g.gif]
